version: '3.1'

services:

  technews-node-dev:
    container_name: technews-node-dev
    build:
      context: ./BACK
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mariadb
    env_file:
      - ./.env

  mariadb:
    container_name: technews-bdd-dev
    build:
      context: BDD
      dockerfile: dev.Dockerfile
    volumes:
      - ./BDD/data:/var/lib/mysql:z
    env_file:
      - ./.env
    expose:
      - 3306

  adminer:
    container_name: technews-adminer-dev
    image: adminer
    depends_on:
      - mariadb
    ports:
      - ${PORT_ADMINER}:8080