version: '3.1'

services:
  web:
    container_name: technews-web-dev
    build:
      context: ./FRONT
      dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - ./FRONT:/app
    ports:
      - 4200:4200
    depends_on:
      - node
    expose:
      - 4200

  node:
    container_name: technews-node-dev
    build:
      context: ./BACK
      dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - ./BACK:/app
    ports:
      - 8080:8080
    expose:
      - 8080
